### ISSUE TITLE
Introduce teacher GUI

### ISSUE THREAD

**Issue by klaraschlueter** [holtwick/peer2school#13]
So far there is only one way to connect to a classroom. We need two different roles, teacher and pupil. This issue does not contain implementing teacher functionality, but providing the infrastructure for two different GUIs with different functions available and different views of the classroom.

**Comment by albrecht-flo** [comment]
Ich würde mich dann mal hier dahinter klemmen.

**Comment by holtwick** [comment]
Es gibt nun ein Flag `state.teacher`. Die Rollen werden momentan noch ganz simpel anhand der URL unterschieden d.h. wenn der URL-Hash auf `.teacher` endet, ist man Lehrer, sonst nicht ;)
