### ISSUE TITLE
Kollaboration

### ISSUE THREAD

**Issue by SebastianSpeitel** [holtwick/peer2school#16]
Hi,
ich komme aus einer Gruppe in der Herausforderung 019 bei wirvsvirus.
Wir haben euch gefunden und gemerkt, dass unsere Zielvorstellungen sich sehr ähneln, deswegen die Frage wo ihr gerade eure interne Kommunikation durchführt und wie wir am besten mit euch in Kontakt treten können.

Grüße
Sebastian

**Comment by klaraschlueter** [comment]
Wir kommunizieren auf Discord, den Link zum Server findet ihr in unserem Slackchannel, peer-to-peer-lernplattform-ab-der-1-klasse. Am einfachsten tretet ihr da bei.
