### ISSUE TITLE
Pupils can raise their hand

### ISSUE THREAD

**Issue by kirschmarsch** [holtwick/peer2school#18]
- pupils can "raise their hand" via a button
- pupils can cancel their raised hand
- the teacher can see all raised hands

**Comment by fehnkera** [comment]
machen wir

**Comment by klaraschlueter** [comment]
The pull request to this issue is merged, isn't it? Are you still working on it, or can I close the issue, @fehnkera ?

**Comment by fehnkera** [comment]
We are still working to improve this issue
