### ISSUE TITLE
Teachers can call a student

### ISSUE THREAD

**Issue by kirschmarsch** [holtwick/peer2school#19]
- the teacher can call a student (independent of raised hands)
- the called student is visible and audible for all other students
- the teacher can finish the calling situation

**Comment by SebastianSpeitel** [comment]
Erstellt nach eurem ersten commit direkt einen PR, damit wir den Verlauf sehen und kommentieren können

Und tagged den PR einfach WIP

**Comment by SebastianSpeitel** [comment]
Wer arbeitet jetzt hier dran? @albrecht-flo

**Comment by fehnkera** [comment]
moin

**Comment by holtwick** [comment]
Zusammenfassung in #58
