### ISSUE TITLE
Setup TURN server

### ISSUE THREAD

**Issue by holtwick** [holtwick/peer2school#2]
For those that do not get through firewalls we'll need a TURN server

**Comment by holtwick** [comment]
Is automatically using Google's servers via simple-peer

**Comment by dmonad** [comment]
There are only free STUN servers because infrastructure would be pretty expensive for public use. But there is https://github.com/coturn/coturn

**Comment by holtwick** [comment]
I added a public TURN server from http://numb.viagenie.ca/

Some commercial services for the case we need them and don't want to maintain 24/7 service for `coturn` installation:
- https://www.twilio.com/stun-turn/pricing
- https://xirsys.com/pricing/

**Comment by holtwick** [comment]
Added the TURN server installation used by Briefing: 

https://github.com/holtwick/briefing/issues/4
https://github.com/holtwick/briefing/issues/28
