### ISSUE TITLE
Teilnehmer haben die Möglichkeit, eigene Namen zu vergeben

### ISSUE THREAD

**Issue by klaraschlueter** [holtwick/peer2school#29]
Bisher werden Identifier angezeigt, diese werden durch Namen ersetzt. Beim Beitreten werden Schüler nach einem Namen gefragt. Ein automatisch abgespieltes Audio "Wie heißt du?" hilft Nichtlesern. Dieser Name wird dann im Chat und beim Aufzeigen verwendet.

**Comment by amacado** [comment]
Ich nehme mich dem an!

**Comment by amacado** [comment]
Pull-Request #31

**Comment by amacado** [comment]
Pull-Request ist eröffnet und wartet auf Review
