### ISSUE TITLE
Alle Teilnehmerinnen und Teilnehmer sehen eine Liste der Schüler im Klassenzimmer

### ISSUE THREAD

**Issue by klaraschlueter** [holtwick/peer2school#30]
Abhängig von #29 (Namensvergabe).

Als Teilnehmerinnen und Teilnehmer (Lehrer/innen und Schüler/innen) können eine Liste mit den Namen aller anderen Teilnehmerinnen und Teilnehmer, die sich im Klassenzimmer befinden, sehen.
Bitte kommuniziert mit den Zuständigen für #19 und #18 (Melden und aufrufen).

**Comment by amacado** [comment]
Ich übernehme das Issue hier zusammen mit #42, die hängen eng zusammen. Kann mich bitte jemand zuweisen und WIP setzen? @klaraschlueter
