### ISSUE TITLE
Aufzeigen in der GUI darstellen

### ISSUE THREAD

**Issue by fehnkera** [holtwick/peer2school#44]
Aktuell gibt es nur den schlecht platzierten Aufzeigeknopf im Chat und eine interne Liste  `pointOuts` die speichert wer aktuell alles aufzeigt. Es müsste für die GUI noch gemacht werden:

1. Den Knopf an eine schönere Stelle verschieben. Soll der Knopf nur für Schüler da sein oder auch für den Lehrer?
2. Die Liste schön grafisch darstellen. In der Liste werden die Ids gespeichert. Ein Mapping von Id zu Name existiert aber schon im Projekt. Auch hier müsste überlegt werden ob nur der Lehrer oder alle die Liste sehen können
(3.) Wohl eher nachrangig, aber wenn der Lehrer jemanden dran nehmen soll müssten die Namen in der Liste anklickbar sein. Dafür müsste aber intern dann auch eine drannehmen-Funktion hinzugefügt werden (evtl durch @fehnkera und @T1bolus )

Bei Rückfragen zur interner Implementierung gerne an @fehnkera und @T1bolus .

**Comment by kirschmarsch** [comment]
Der Lehrer braucht keinen Melden-Knopf.
Zumindest der Lehrer muss sehen, wer sich meldet, gerne auch die anderen Schüler. Vielleicht einfach durch eine Markierung in der Liste aus #30?

**Comment by gruenerf** [comment]
Das kann ich dann gerne übernehmen

**Comment by amacado** [comment]
Ich denke, dass eine Kombination mit #30 sehr viel Sinn macht. Bitte dazu bei mir melden @gruenerf
