### ISSUE TITLE
Integrate basic Whiteboard based on vue.js

### ISSUE THREAD

**Issue by kaltenFra** [holtwick/peer2school#7]
- basierend auf vue.js 
- gerne mit OpenSource

**Comment by Hagelsturm2018** [comment]
Eine Möglichkeit: https://github.com/nikitastryuk/Whiteboard

**Comment by albrecht-flo** [comment]
Könntest du kurz in den Issues Channel auf Discord kommen, wir hätten ein paar Fragen zu dem Whiteboard und du hast da schon mehr Erfahrung.

**Comment by holtwick** [comment]
@Hagelsturm2018 ich hab mir das https://github.com/nikitastryuk/Whiteboard kurz angesehen und muss sagen es ist auf den ersten Blick toll. Schön einfach, gut erweiterbar, UNDO/REDO gibt es auch. 

Hier noch mal der Vollständigkeit halber eine Liste die ich gestern zusammengestellt habe, ohne Gewähr und ohne Gewichtung:

- [ ] Drawing 

  - [ ] draw.io <https://app.diagrams.net/>

  - [ ] <https://github.com/jgraph>

  - [ ] <https://github.com/jgraph/mxgraph>

  - [ ] <https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html>

  - [ ] <https://github.com/yjs/website/blob/master/src/components/demos/demo-drawing.js>

- [ ] Sketch

  - [ ] <https://github.com/yiom/sketchpad>

  - [ ] <https://github.com/tsand/responsive-sketchpad>

  - [ ] <https://github.com/literallycanvas/literallycanvas>

  - [ ] <https://github.com/devforth/painterro>

  - [ ] <https://github.com/cracker0dks/whiteboard>

**Comment by klaraschlueter** [comment]
To me it makes sense, that in a first version, only the teacher can write on the blackboard - otherwise we might have a lot of pupils editing the whiteboard for fun all the time. What do you think?
This would of course depend on issue #13 .

**Comment by holtwick** [comment]
@klaraschlueter ich denke auch, für die erste Demo reicht es das nur der Lehrer schreiben kann.

**Comment by klaraschlueter** [comment]
Closed by release 0.3.0
